# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNJetpack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNJetpack


  target 'RNJetpackTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNJetpack-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNJetpack-tvOS

  target 'RNJetpack-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
